export const reset_r = [
  { id: 1, lvl: "", device: "", desc: "", type: "", notes: "" },
  { id: 2, lvl: "", device: "", desc: "", type: "", notes: "" },
  { id: 3, lvl: "", device: "", desc: "", type: "", notes: "" },
  { id: 4, lvl: "", device: "", desc: "", type: "", notes: "" },
  { id: 5, lvl: "", device: "", desc: "", type: "", notes: "" },
  { id: 6, lvl: "", device: "", desc: "", type: "", notes: "" },
  { id: 7, lvl: "", device: "", desc: "", type: "", notes: "" },
  { id: 8, lvl: "", device: "", desc: "", type: "", notes: "" },
  { id: 9, lvl: "", device: "", desc: "", type: "", notes: "" },
  { id: 10, lvl: "", device: "", desc: "", type: "", notes: "" },
  { id: 11, lvl: "", device: "", desc: "", type: "", notes: "" },
  { id: 12, lvl: "", device: "", desc: "", type: "", notes: "" },
  { id: 13, lvl: "", device: "", desc: "", type: "", notes: "" },
  { id: 14, lvl: "", device: "", desc: "", type: "", notes: "" },
  { id: 15, lvl: "", device: "", desc: "", type: "", notes: "" },
  { id: 16, lvl: "", device: "", desc: "", type: "", notes: "" },
];

export const reset_i = [
  { id: 1, lvl: "", device: "", desc: "", type: "", notes: "" },
  { id: 2, lvl: "", device: "", desc: "", type: "", notes: "" },
  { id: 3, lvl: "", device: "", desc: "", type: "", notes: "" },
  { id: 4, lvl: "", device: "", desc: "", type: "", notes: "" },
  { id: 5, lvl: "", device: "", desc: "", type: "", notes: "" },
  { id: 6, lvl: "", device: "", desc: "", type: "", notes: "" },
  { id: 7, lvl: "", device: "", desc: "", type: "", notes: "" },
  { id: 8, lvl: "", device: "", desc: "", type: "", notes: "" },
  { id: 9, lvl: "", device: "", desc: "", type: "", notes: "" },
  { id: 10, lvl: "", device: "", desc: "", type: "", notes: "" },
  { id: 11, lvl: "", device: "", desc: "", type: "", notes: "" },
  { id: 12, lvl: "", device: "", desc: "", type: "", notes: "" },
  { id: 13, lvl: "", device: "", desc: "", type: "", notes: "" },
  { id: 14, lvl: "", device: "", desc: "", type: "", notes: "" },
  { id: 15, lvl: "", device: "", desc: "", type: "", notes: "" },
  { id: 16, lvl: "", device: "", desc: "", type: "", notes: "" },
  { id: 17, lvl: "", device: "", desc: "", type: "", notes: "" },
  { id: 18, lvl: "", device: "", desc: "", type: "", notes: "" },
  { id: 19, lvl: "", device: "", desc: "", type: "", notes: "" },
  { id: 20, lvl: "", device: "", desc: "", type: "", notes: "" },
  { id: 21, lvl: "", device: "", desc: "", type: "", notes: "" },
  { id: 22, lvl: "", device: "", desc: "", type: "", notes: "" },
  { id: 23, lvl: "", device: "", desc: "", type: "", notes: "" },
  { id: 24, lvl: "", device: "", desc: "", type: "", notes: "" },
  { id: 25, lvl: "", device: "", desc: "", type: "", notes: "" },
  { id: 26, lvl: "", device: "", desc: "", type: "", notes: "" },
  { id: 27, lvl: "", device: "", desc: "", type: "", notes: "" },
  { id: 28, lvl: "", device: "", desc: "", type: "", notes: "" },
  { id: 29, lvl: "", device: "", desc: "", type: "", notes: "" },
  { id: 30, lvl: "", device: "", desc: "", type: "", notes: "" },
  { id: 31, lvl: "", device: "", desc: "", type: "", notes: "" },
  { id: 32, lvl: "", device: "", desc: "", type: "", notes: "" },
  { id: 33, lvl: "", device: "", desc: "", type: "", notes: "" },
  { id: 34, lvl: "", device: "", desc: "", type: "", notes: "" },
  { id: 35, lvl: "", device: "", desc: "", type: "", notes: "" },
  { id: 36, lvl: "", device: "", desc: "", type: "", notes: "" },
  { id: 37, lvl: "", device: "", desc: "", type: "", notes: "" },
  { id: 38, lvl: "", device: "", desc: "", type: "", notes: "" },
  { id: 39, lvl: "", device: "", desc: "", type: "", notes: "" },
  { id: 40, lvl: "", device: "", desc: "", type: "", notes: "" },
  { id: 41, lvl: "", device: "", desc: "", type: "", notes: "" },
  { id: 42, lvl: "", device: "", desc: "", type: "", notes: "" },
  { id: 43, lvl: "", device: "", desc: "", type: "", notes: "" },
  { id: 44, lvl: "", device: "", desc: "", type: "", notes: "" },
  { id: 45, lvl: "", device: "", desc: "", type: "", notes: "" },
  { id: 46, lvl: "", device: "", desc: "", type: "", notes: "" },
  { id: 47, lvl: "", device: "", desc: "", type: "", notes: "" },
  { id: 48, lvl: "", device: "", desc: "", type: "", notes: "" },
];

export const reset_o = [
  { id: 1, lvl: "", device: "", desc: "", type: "", notes: "" },
  { id: 2, lvl: "", device: "", desc: "", type: "", notes: "" },
  { id: 3, lvl: "", device: "", desc: "", type: "", notes: "" },
  { id: 4, lvl: "", device: "", desc: "", type: "", notes: "" },
  { id: 5, lvl: "", device: "", desc: "", type: "", notes: "" },
  { id: 6, lvl: "", device: "", desc: "", type: "", notes: "" },
  { id: 7, lvl: "", device: "", desc: "", type: "", notes: "" },
  { id: 8, lvl: "", device: "", desc: "", type: "", notes: "" },
  { id: 9, lvl: "", device: "", desc: "", type: "", notes: "" },
  { id: 10, lvl: "", device: "", desc: "", type: "", notes: "" },
  { id: 11, lvl: "", device: "", desc: "", type: "", notes: "" },
  { id: 12, lvl: "", device: "", desc: "", type: "", notes: "" },
  { id: 13, lvl: "", device: "", desc: "", type: "", notes: "" },
  { id: 14, lvl: "", device: "", desc: "", type: "", notes: "" },
  { id: 15, lvl: "", device: "", desc: "", type: "", notes: "" },
  { id: 16, lvl: "", device: "", desc: "", type: "", notes: "" },
  { id: 17, lvl: "", device: "", desc: "", type: "", notes: "" },
  { id: 18, lvl: "", device: "", desc: "", type: "", notes: "" },
  { id: 19, lvl: "", device: "", desc: "", type: "", notes: "" },
  { id: 20, lvl: "", device: "", desc: "", type: "", notes: "" },
  { id: 21, lvl: "", device: "", desc: "", type: "", notes: "" },
  { id: 22, lvl: "", device: "", desc: "", type: "", notes: "" },
  { id: 23, lvl: "", device: "", desc: "", type: "", notes: "" },
  { id: 24, lvl: "", device: "", desc: "", type: "", notes: "" },
  { id: 25, lvl: "", device: "", desc: "", type: "", notes: "" },
  { id: 26, lvl: "", device: "", desc: "", type: "", notes: "" },
  { id: 27, lvl: "", device: "", desc: "", type: "", notes: "" },
  { id: 28, lvl: "", device: "", desc: "", type: "", notes: "" },
  { id: 29, lvl: "", device: "", desc: "", type: "", notes: "" },
  { id: 30, lvl: "", device: "", desc: "", type: "", notes: "" },
  { id: 31, lvl: "", device: "", desc: "", type: "", notes: "" },
  { id: 32, lvl: "", device: "", desc: "", type: "", notes: "" },
];

export const reset_name = {
  acp_name: "",
  acp_location: "",
  // acp_model:"",
  acp_ip: "",
};
