
export const MANUFACTURERS=[
	"--Select--",	
	"HID",
	"Kantech",
	"SoftwareHouse",
	"Bosch",
    "DMP"
]

export const PRODUCTS={
	"--Select--":[
		{
				
		},
	],
	"Kantech":[
		{

		},
		{
			key: '1',
			mfg:'Kantech',
			name: 'T.REX',
			standby: 50,
			alarm: 50,		
		},
	],
	"HID": [
		{

		},
		{
			key: '1',
			mfg:'HID',
			name: 'R10 iclass SE',
			standby: 45,
			alarm: 45,		
		},
		{
			key: '2',
			mfg:'HID',
			name: 'R40 iclass SE',
			standby: 65,
			alarm: 65,		
		},
		{
			key: '3',
			mfg:'HID',
			name: 'RK40 iclass SE',
			standby: 100,
			alarm: 100,		
		},
		{
			key: '4',
			mfg:'HID',
			name: 'RP10 Multiclass SE',
			standby: 75,
			alarm: 75,		
		},
		{
			key: '5',
			mfg:'HID',
			name: 'RP40 Multiclass SE',
			standby: 85,
			alarm: 85,		
		},
		{
			key: '6',
			mfg:'HID',
			name: 'RPK40 Multiclass SE',
			standby: 95,
			alarm: 95,		
		},
		{
			key: '7',
			mfg:'HID',
			name: 'Signo 20',
			standby: 70,
			alarm: 70,		
		},
		{
			key: '8',
			mfg:'HID',
			name: 'Signo 20K',
			standby: 75,
			alarm: 75,		
		},
		{
			key: '9',
			mfg:'HID',
			name: 'Signo 40',
			standby: 75,
			alarm: 75,		
		},
		{
			key: '10',
			mfg:'HID',
			name: 'Signo 40K',
			standby: 80,
			alarm: 80,		
		},
		
	  ],
	"SoftwareHouse" : [
		{

		},
		{
			key: '1',
			mfg:'SWH',
			name: 'iStar Ultra GCM',
			standby: 500,
			alarm: 500,		
		},
		{
			key: '2',
			mfg:'SWH',
			name: 'iStar Ultra ACM',
			standby: 500,
			alarm: 500,		
		},
		{
			key: '3',
			mfg:'SWH',
			name: 'iStar Ultra-SE ACM-SE',
			standby: 500,
			alarm: 500,		
		},
		{
			key: '4',
			mfg:'SWH',
			name: 'AS0073-000 (I/8)',
			standby: 180,
			alarm: 180,		
		},
		{
			key: '5',
			mfg:'SWH',
			name: 'AS0074-000 (R/8)',
			standby: 300,
			alarm: 300,		
		},
		{
			key: '6',
			mfg:'SWH',
			name: 'iStar Edge',
			standby: 200,
			alarm: 200,		
		},
		{
			key: '7',
			mfg:'SWH',
			name: 'iStar Edge G2',
			standby: 500,
			alarm: 500,		
		},
		{
			key: '8',
			mfg:'SWH',
			name: 'RM-4E',
			standby: 280,
			alarm: 280,		
		},
		{
			key: '9',
			mfg:'SWH',
			name: 'iStar Pro GCM',
			standby: 290,
			alarm: 290,		
		},
		{
			key: '10',
			mfg:'SWH',
			name: 'iStar Pro ACM',
			standby: 100,
			alarm: 100,		
		},
		
	  ],
	  "Bosch" : [
		{

		},
		
{
    key: 1,
    mfg:'Bosch',
    name: 'B201 2-Wire Powered Loop',
    standby: 18,
    alarm: 35,		
},
{
    key: 2,
    mfg:'Bosch',
    name: 'B208 8 Input Module For Sdi2 Bus',
    standby: 35,
    alarm: 35,		
},
{
    key: 3,
    mfg:'Bosch',
    name: 'B299 Popex Module For B9512G And B8512G',
    standby: 40,
    alarm: 140,		
},
{
    key: 4,
    mfg:'Bosch',
    name: 'B308 8 Relay Module For Sdi2',
    standby: 22,
    alarm: 22,		
},
{
    key: 5,
    mfg:'Bosch',
    name: 'B308-1 Single Relay On B308',
    standby: 16.25,
    alarm: 16.25,		
},
{
    key: 6,
    mfg:'Bosch',
    name: 'B3512 16 Point Control Communicator',
    standby: 125,
    alarm: 155,		
},
{
    key: 7,
    mfg:'Bosch',
    name: 'B426 Conettix Ip Ethernet Interface',
    standby: 100,
    alarm: 100,		
},
{
    key: 8,
    mfg:'Bosch',
    name: 'B430 Plug-In Communicator, Telephone',
    standby: 5,
    alarm: 25,		
},
{
    key: 9,
    mfg:'Bosch',
    name: 'B440 Plug-In Cellular Communicator, Verizon Evdo (3G)',
    standby: 35,
    alarm: 150,		
},
{
    key: 10,
    mfg:'Bosch',
    name: 'B441 Plug-In Cellular Communicator, Verizon Cdma',
    standby: 35,
    alarm: 150,		
},
{
    key: 11,
    mfg:'Bosch',
    name: 'B442 Plug-In Cellular Module, Gprs',
    standby: 35,
    alarm: 150,		
},
{
    key: 12,
    mfg:'Bosch',
    name: 'B443 Plug-In Cellular Communicator, Hspa+ (3G/4G)',
    standby: 35,
    alarm: 150,		
},
{
    key: 13,
    mfg:'Bosch',
    name: 'B443-ATT-SIM Hspa+ Plug-In W/ Att Sim',
    standby: 35,
    alarm: 150,		
},
{
    key: 14,
    mfg:'Bosch',
    name: 'B450 Plug-In Communication Module Adapter For B Series, G Series And Fpd7024 Panels',
    standby: 30,
    alarm: 30,		
},
{
    key: 15,
    mfg:'Bosch',
    name: 'B450-C Cellular Add-On Kit Includes B440 Plus B450',
    standby: 65,
    alarm: 180,		
},
{
    key: 16,
    mfg:'Bosch',
    name: 'B450-C1 Cellular Add-On Kit Includes B441 Plus B450',
    standby: 65,
    alarm: 180,		
},
{
    key: 17,
    mfg:'Bosch',
    name: 'B4512 28 Point Control Communicator',
    standby: 125,
    alarm: 155,		
},
{
    key: 18,
    mfg:'Bosch',
    name: 'B520 Sdi2 Auxiliary Power Supply 2.0 Amps',
    standby: 15,
    alarm: 15,		
},
{
    key: 19,
    mfg:'Bosch',
    name: 'B5512 48 Point Control Communicator',
    standby: 125,
    alarm: 155,		
},
{
    key: 20,
    mfg:'Bosch',
    name: 'B600 Zonex Module For B9512G And B8512G',
    standby: 10,
    alarm: 12,		
},
{
    key: 21,
    mfg:'Bosch',
    name: 'B6512 96 Point Control Communicator, 4 Doors',
    standby: 125,
    alarm: 155,		
},
{
    key: 22,
    mfg:'Bosch',
    name: 'B810 Receiver For Use On B Series And Gv4',
    standby: 100,
    alarm: 100,		
},
{
    key: 23,
    mfg:'Bosch',
    name: 'B820 Sdi2 Inovonics Interface',
    standby: 100,
    alarm: 100,		
},
{
    key: 24,
    mfg:'Bosch',
    name: 'B8512G Intrusion/Fire/Access Control Panel 99 Points 8 Doors',
    standby: 190,
    alarm: 265,		
},
{
    key: 25,
    mfg:'Bosch',
    name: 'B8512G-BP Fire Kit (B8512G, D8109, D1640, D122, D161(2), B430 (2), D101F)',
    standby: 200,
    alarm: 315,		
},
{
    key: 26,
    mfg:'Bosch',
    name: 'B8512G-C Kit (B8512G, B8103, D1640)',
    standby: 190,
    alarm: 265,		
},
{
    key: 27,
    mfg:'Bosch',
    name: 'B8512G-CC Kit (B8512G, B8103, B440, D1640)',
    standby: 225,
    alarm: 415,		
},
{
    key: 28,
    mfg:'Bosch',
    name: 'B8512G-CC1 Kit (B8512G, B8103, B441, D1640)',
    standby: 225,
    alarm: 415,		
},
{
    key: 29,
    mfg:'Bosch',
    name: 'B8512G-CP Kit (B8512G, B8103, B430, D1640)',
    standby: 195,
    alarm: 290,		
},
{
    key: 30,
    mfg:'Bosch',
    name: 'B8512G-ECC Kit (B8512G-E, B8103, B440, D1640)',
    standby: 225,
    alarm: 415,		
},
{
    key: 31,
    mfg:'Bosch',
    name: 'B8512G-ECC1 Kit (B8512G-E, B8103, B441, D1640)',
    standby: 225,
    alarm: 415,		
},
{
    key: 32,
    mfg:'Bosch',
    name: 'B8512G-ECP Kit (B8512G-E, B8103, B430, D1640)',
    standby: 125,
    alarm: 255,		
},
{
    key: 33,
    mfg:'Bosch',
    name: 'B901 Door Control Module Sdi2/Sdi',
    standby: 110,
    alarm: 110,		
},
{
    key: 34,
    mfg:'Bosch',
    name: 'B915 Basic Text Keypad',
    standby: 35,
    alarm: 70,		
},
{
    key: 35,
    mfg:'Bosch',
    name: 'B915I Basic Text Keypad (Icon Keys)',
    standby: 35,
    alarm: 70,		
},
{
    key: 36,
    mfg:'Bosch',
    name: 'B920 2 Line Alpha Numeric Keypad (Sd12)',
    standby: 35,
    alarm: 70,		
},
{
    key: 37,
    mfg:'Bosch',
    name: 'B921C 2-Line Lcd Capacitive Touch Keypad',
    standby: 35,
    alarm: 70,		
},
{
    key: 38,
    mfg:'Bosch',
    name: 'B925F Combination Fire And Intrusion Keypad/Annunciator For B8512G And B9512G',
    standby: 35,
    alarm: 70,		
},
{
    key: 39,
    mfg:'Bosch',
    name: 'B926F Fire Keypad/Annunciator For B8512G And B9512G',
    standby: 35,
    alarm: 70,		
},
{
    key: 40,
    mfg:'Bosch',
    name: 'B930 Atm Style-Alpha Numeric Keypad (Sd12)',
    standby: 35,
    alarm: 80,		
},
{
    key: 41,
    mfg:'Bosch',
    name: 'B942 Color Graphic Touch Screen Keypad With Prox (Black)',
    standby: 200,
    alarm: 300,		
},
{
    key: 42,
    mfg:'Bosch',
    name: 'B942W Color Graphic Touch Screen Keypad With Prox (White)',
    standby: 200,
    alarm: 300,		
},
{
    key: 43,
    mfg:'Bosch',
    name: 'B9512G Intrusion/Fire/Access Control Panel 599 Points 32 Doors',
    standby: 190,
    alarm: 265,		
},
{
    key: 44,
    mfg:'Bosch',
    name: 'B9512G-BP Fire Kit (B9512G, D8109, D1640, D122, D161(2), B430 (2), D101F)',
    standby: 200,
    alarm: 315,		
},
{
    key: 45,
    mfg:'Bosch',
    name: 'B9512G-C Kit (B9512G, B8103, D1640)',
    standby: 190,
    alarm: 265,		
},
{
    key: 46,
    mfg:'Bosch',
    name: 'B9512G-CC Kit (B9512G, B8103, B440, D1640)',
    standby: 225,
    alarm: 415,		
},
{
    key: 47,
    mfg:'Bosch',
    name: 'B9512G-CC1 Kit (B9512G, B8103, B441, D1640)',
    standby: 225,
    alarm: 415,		
},
{
    key: 48,
    mfg:'Bosch',
    name: 'B9512G-CC-930 B9512G Cellular Kit With B930, B440',
    standby: 260,
    alarm: 495,		
},
{
    key: 49,
    mfg:'Bosch',
    name: 'B9512G-CP Kit (B9512G, B8103, B430, D1640)',
    standby: 125,
    alarm: 155,		
},
{
    key: 50,
    mfg:'Bosch',
    name: 'B9512G-ECC Kit (B9512G-E, B8103, B440, D1640)',
    standby: 225,
    alarm: 415,		
},
{
    key: 51,
    mfg:'Bosch',
    name: 'B9512G-ECC1 Kit (B9512G-E, B8103, B441, D1640)',
    standby: 225,
    alarm: 415,		
},
{
    key: 52,
    mfg:'Bosch',
    name: 'CAB-A null',
    standby: 0,
    alarm: 50,		
},
{
    key: 53,
    mfg:'Bosch',
    name: 'CAB-F null',
    standby: 0,
    alarm: 65,		
},
{
    key: 54,
    mfg:'Bosch',
    name: 'D1003 null',
    standby: 0,
    alarm: 30,		
},
{
    key: 55,
    mfg:'Bosch',
    name: 'D1004 null',
    standby: 0,
    alarm: 60,		
},
{
    key: 56,
    mfg:'Bosch',
    name: 'D1005 null',
    standby: 0,
    alarm: 30,		
},
{
    key: 57,
    mfg:'Bosch',
    name: 'D1255 Alpha Comm Cntr, Off-White',
    standby: 104,
    alarm: 225,		
},
{
    key: 58,
    mfg:'Bosch',
    name: 'D1255RB Full Function Fire Keypad With Vacuum Florescent Display',
    standby: 104,
    alarm: 225,		
},
{
    key: 59,
    mfg:'Bosch',
    name: 'D1255RB Full Function Fire Keypad With Vacuum Florescent Display',
    standby: 104,
    alarm: 225,		
},
{
    key: 60,
    mfg:'Bosch',
    name: 'D1256 Fire Comm Cntr, Red',
    standby: 104,
    alarm: 225,		
},
{
    key: 61,
    mfg:'Bosch',
    name: 'D1256RB Fire Annunciator/Keypad With Vacuum Florescent Display',
    standby: 104,
    alarm: 225,		
},
{
    key: 62,
    mfg:'Bosch',
    name: 'd1257 Remote Fire Annctr, Red',
    standby: 104,
    alarm: 225,		
},
{
    key: 63,
    mfg:'Bosch',
    name: 'D125B 12/24V Dual Initiatng Mod',
    standby: 25,
    alarm: 168,		
},
{
    key: 64,
    mfg:'Bosch',
    name: 'D1260 Atm Style Alpha Command Center With Lcd Display - Off-White Enclosure',
    standby: 140,
    alarm: 250,		
},
{
    key: 65,
    mfg:'Bosch',
    name: 'D1260B Atm Style Alpha Command Center With Lcd Display - Grey And White Enclosure',
    standby: 140,
    alarm: 250,		
},
{
    key: 66,
    mfg:'Bosch',
    name: 'D1265 Touch Screen Keypad',
    standby: 135,
    alarm: 300,		
},
{
    key: 67,
    mfg:'Bosch',
    name: 'D127 Reversing Relay Module',
    standby: 5,
    alarm: 55,		
},
{
    key: 68,
    mfg:'Bosch',
    name: 'D129 Dual Class A Fire Loop',
    standby: 23,
    alarm: 25,		
},
{
    key: 69,
    mfg:'Bosch',
    name: 'D132A Smoke Det. Rev. Module',
    standby: 10,
    alarm: 70,		
},
{
    key: 70,
    mfg:'Bosch',
    name: 'D185 Rev Polarity Intrfc Mod',
    standby: 245,
    alarm: 300,		
},
{
    key: 71,
    mfg:'Bosch',
    name: 'D192G Bell Suprvsn Mod 12V/24V, 3A',
    standby: 25,
    alarm: 100,		
},
{
    key: 72,
    mfg:'Bosch',
    name: 'D265AW Smoke Det Head-Photoelect, 12V/24V',
    standby: 0.55,
    alarm: 15,		
},
{
    key: 73,
    mfg:'Bosch',
    name: 'D266W Smoke Det Head Photo/Heat, 12V/24V',
    standby: 0.4,
    alarm: 0,		
},
{
    key: 74,
    mfg:'Bosch',
    name: 'D270 Smoke Base 12V 4Wire 4 In, 12V/24V',
    standby: 0.16,
    alarm: 0,		
},
{
    key: 75,
    mfg:'Bosch',
    name: 'D271S 12V 4W Znx Smk Single Base',
    standby: 1,
    alarm: 70,		
},
{
    key: 76,
    mfg:'Bosch',
    name: 'D273IS Smoke Det 4 Wire (Ds284Is)12V/24V',
    standby: 0.9,
    alarm: 54,		
},
{
    key: 77,
    mfg:'Bosch',
    name: 'D273TH Smoke Det Photo/Heat 4W, 12V/24V',
    standby: 0.9,
    alarm: 0,		
},
{
    key: 78,
    mfg:'Bosch',
    name: 'D273THC Smoke Det 4 Wire (Ds284Thc), 12V/24V',
    standby: 0,
    alarm: 44,		
},
{
    key: 79,
    mfg:'Bosch',
    name: 'D273THCS Smoke Det 4 Wire (Ds284Thcs), 12V/24V',
    standby: 1.3,
    alarm: 50,		
},
{
    key: 80,
    mfg:'Bosch',
    name: 'D273THE 4W Smk Det (Ds284The), 12V/24V',
    standby: 0,
    alarm: 80,		
},
{
    key: 81,
    mfg:'Bosch',
    name: 'D273THSR 4W Smk Det (Ds284Thsr), 12V/24V',
    standby: 2,
    alarm: 15,		
},
{
    key: 82,
    mfg:'Bosch',
    name: 'D285TH Smoke Det Head Photo/Heat',
    standby: 0,
    alarm: 0,		
},
{
    key: 83,
    mfg:'Bosch',
    name: 'D291S 24V Znx Id Base Single',
    standby: 0,
    alarm: 8,		
},
{
    key: 84,
    mfg:'Bosch',
    name: 'D292 Smoke Det Base 4Wire 6 In',
    standby: 0.39,
    alarm: 8,		
},
{
    key: 85,
    mfg:'Bosch',
    name: 'D293A Smoke Det Base W/Relay 4W',
    standby: 0.39,
    alarm: 8,		
},
{
    key: 86,
    mfg:'Bosch',
    name: 'D293E Smoke Base W/Pwrsprvsn 4W',
    standby: 0.39,
    alarm: 5,		
},
{
    key: 87,
    mfg:'Bosch',
    name: 'D293S Smoke Base W/Sounder 4W',
    standby: 0.29,
    alarm: 28,		
},
{
    key: 88,
    mfg:'Bosch',
    name: 'D294 Pwr Sprvision Mod 24V',
    standby: 0.22,
    alarm: 0.15,		
},
{
    key: 89,
    mfg:'Bosch',
    name: 'D297 null',
    standby: 70,
    alarm: 95,		
},
{
    key: 90,
    mfg:'Bosch',
    name: 'D298M 24V 4W Znx Smk Master Base (Ds)',
    standby: 0.1,
    alarm: 8,		
},
{
    key: 91,
    mfg:'Bosch',
    name: 'D298S 24V 4W Znx Smk Single Base (Ds)',
    standby: 0.39,
    alarm: 55,		
},
{
    key: 92,
    mfg:'Bosch',
    name: 'D299 Aux Relay Mod D290/291',
    standby: 10,
    alarm: 7.6,		
},
{
    key: 93,
    mfg:'Bosch',
    name: 'D300 Duct Det Housing',
    standby: 0.138,
    alarm: 28,		
},
{
    key: 94,
    mfg:'Bosch',
    name: 'D302 Sampling Tube 5 Ft 5/Pkg',
    standby: 0,
    alarm: 28,		
},
{
    key: 95,
    mfg:'Bosch',
    name: 'D401 Plate, Semi-Flush',
    standby: 0,
    alarm: 10,		
},
{
    key: 96,
    mfg:'Bosch',
    name: 'D402 Backbox Surfc In/Out Door',
    standby: 0,
    alarm: 22,		
},
{
    key: 97,
    mfg:'Bosch',
    name: 'D403 Backbox, Smt Indoor',
    standby: 0,
    alarm: 22,		
},
{
    key: 98,
    mfg:'Bosch',
    name: 'D422A Horn Strobe 15/75 Cd 24V',
    standby: 0,
    alarm: 41,		
},
{
    key: 99,
    mfg:'Bosch',
    name: 'D440 Bell, Red Fire 12V 6 Inch',
    standby: 0,
    alarm: 102,		
},
{
    key: 100,
    mfg:'Bosch',
    name: 'D441 Bell, Red 24V 6 Inch',
    standby: 0,
    alarm: 75,		
},
{
    key: 101,
    mfg:'Bosch',
    name: 'D442 Bell, Red Fire 12V 10 In',
    standby: 0,
    alarm: 100,		
},
{
    key: 102,
    mfg:'Bosch',
    name: 'D448 Horn, Mini 12V',
    standby: 0,
    alarm: 91,		
},
{
    key: 103,
    mfg:'Bosch',
    name: 'D448W Horn, Mini 12V White',
    standby: 0,
    alarm: 140,		
},
{
    key: 104,
    mfg:'Bosch',
    name: 'D449 Horn, Mini 24V',
    standby: 0,
    alarm: 77,		
},
{
    key: 105,
    mfg:'Bosch',
    name: 'D449W Horn, Mini 24V White',
    standby: 0,
    alarm: 175,		
},
{
    key: 106,
    mfg:'Bosch',
    name: 'D457 Horn, Multi-Tone 12/24V',
    standby: 0,
    alarm: 102,		
},
{
    key: 107,
    mfg:'Bosch',
    name: 'D463G Dbl Action Lift Kit, Green',
    standby: 0,
    alarm: 25,		
},
{
    key: 108,
    mfg:'Bosch',
    name: 'D463Y Dbl Action Lift Kit, Yellow',
    standby: 0,
    alarm: 38,		
},
{
    key: 109,
    mfg:'Bosch',
    name: 'D466B Backbox Man Station Blue',
    standby: 0,
    alarm: 273,		
},
{
    key: 110,
    mfg:'Bosch',
    name: 'D466G Backbox Man Station Green',
    standby: 0,
    alarm: 183,		
},
{
    key: 111,
    mfg:'Bosch',
    name: 'D466Y Backbox Man Station Yellow',
    standby: 0,
    alarm: 128,		
},
{
    key: 112,
    mfg:'Bosch',
    name: 'D467 Manual Sta. Weathr W/Backbox',
    standby: 0,
    alarm: 48,		
},
{
    key: 113,
    mfg:'Bosch',
    name: 'D468 Manual Sta. Explosion Proof',
    standby: 0,
    alarm: 320,		
},
{
    key: 114,
    mfg:'Bosch',
    name: 'D470 Horn,Semi-Flush, 12/24V',
    standby: 0,
    alarm: 238,		
},
{
    key: 115,
    mfg:'Bosch',
    name: 'D475A Horn Strobe 12V 15/75 Cd',
    standby: 0,
    alarm: 202,		
},
{
    key: 116,
    mfg:'Bosch',
    name: 'D539S Horn, Synchronized 12V',
    standby: 0,
    alarm: 65,		
},
{
    key: 117,
    mfg:'Bosch',
    name: 'D541S Horn, Synchronized 24V',
    standby: 0,
    alarm: 81,		
},
{
    key: 118,
    mfg:'Bosch',
    name: 'D542S Horn, Synchronized W/Proff 12V',
    standby: 0,
    alarm: 133,		
},
{
    key: 119,
    mfg:'Bosch',
    name: 'D543S Horn, Synchronized W/Proff 24V',
    standby: 0,
    alarm: 161,		
},
{
    key: 120,
    mfg:'Bosch',
    name: 'D570S 24V Horn Sync Strb 15 Cd 2W',
    standby: 0,
    alarm: 67,		
},
{
    key: 121,
    mfg:'Bosch',
    name: 'D571S 24V Horn Sync Strb 15/75 2W',
    standby: 0,
    alarm: 238,		
},
{
    key: 122,
    mfg:'Bosch',
    name: 'D572S 24V Horn Sync Strb 110Cd 2W',
    standby: 0,
    alarm: 67,		
},
{
    key: 123,
    mfg:'Bosch',
    name: 'D573S 24V Horn Sync Strb 30 Cd 2W',
    standby: 0,
    alarm: 204,		
},
{
    key: 124,
    mfg:'Bosch',
    name: 'D579S Horn/Strobe 15 Cd Ceiling',
    standby: 0,
    alarm: 50,		
},
{
    key: 125,
    mfg:'Bosch',
    name: 'D580S Horn/Strobe 30 Cd Ceiling',
    standby: 0,
    alarm: 65,		
},
{
    key: 126,
    mfg:'Bosch',
    name: 'D581S Horn/Strobe 75 Cd Ceiling',
    standby: 0,
    alarm: 133,		
},
{
    key: 127,
    mfg:'Bosch',
    name: 'D582S Horn/Strobe 100 Cd Ceilng',
    standby: 0,
    alarm: 81,		
},
{
    key: 128,
    mfg:'Bosch',
    name: 'D654 Amplifier Crd 40 Watt Whlk',
    standby: 0,
    alarm: 80,		
},
{
    key: 129,
    mfg:'Bosch',
    name: 'D655 Amplifier Crd 80 Watt Whlk',
    standby: 0,
    alarm: 115,		
},
{
    key: 130,
    mfg:'Bosch',
    name: 'D656 Self Amp Speaker Card',
    standby: 0,
    alarm: 135,		
},
{
    key: 131,
    mfg:'Bosch',
    name: 'D657 Remote Microphone Red',
    standby: 0,
    alarm: 133,		
},
{
    key: 132,
    mfg:'Bosch',
    name: 'D658 Remote Microphone Black',
    standby: 0,
    alarm: 225,		
},
{
    key: 133,
    mfg:'Bosch',
    name: 'D7050 Multiplex P/E Smoke Head',
    standby: 0.55,
    alarm: 0.55,		
},
{
    key: 134,
    mfg:'Bosch',
    name: 'D7050-B6 2 Wire Base For 7050',
    standby: 0,
    alarm: 0,		
},
{
    key: 135,
    mfg:'Bosch',
    name: 'D7050DH Multi P/E Smk Head (Duct)',
    standby: 0.55,
    alarm: 0.55,		
},
{
    key: 136,
    mfg:'Bosch',
    name: 'D7050TH Multiplex P/E Smk W/Heat',
    standby: 0.55,
    alarm: 0.55,		
},
{
    key: 137,
    mfg:'Bosch',
    name: 'D8004 Transformer Kit Ul Approv',
    standby: 0,
    alarm: 0,		
},
{
    key: 138,
    mfg:'Bosch',
    name: 'D8125 Popex Zone Expander',
    standby: 47,
    alarm: 48,		
},
{
    key: 139,
    mfg:'Bosch',
    name: 'D8125MUX Zonex To Dual Multi-Inferface',
    standby: 140,
    alarm: 140,		
},
{
    key: 140,
    mfg:'Bosch',
    name: 'D8128D Octopopit, 63 Or 119 Pt Bus W/Indep. Pt Disabler',
    standby: 25,
    alarm: 50,		
},
{
    key: 141,
    mfg:'Bosch',
    name: 'D8129 Octo-Relay',
    standby: 20,
    alarm: 220,		
},
{
    key: 142,
    mfg:'Bosch',
    name: 'D8130 Release Module',
    standby: 7,
    alarm: 60,		
},
{
    key: 143,
    mfg:'Bosch',
    name: 'D9127T Popit Ii Ul W/Tmpr,L Current',
    standby: 0.5,
    alarm: 0.8,		
},
{
    key: 144,
    mfg:'Bosch',
    name: 'D9127U Popit Ii Ul, Low Current',
    standby: 0.5,
    alarm: 0.8,		
},
{
    key: 145,
    mfg:'Bosch',
    name: 'D9210C Access Control Interface Module',
    standby: 100,
    alarm: 120,		
},
{
    key: 146,
    mfg:'Bosch',
    name: 'D928 Dual Phone Line Switcher',
    standby: 14,
    alarm: 45,		
},
{
    key: 147,
    mfg:'Bosch',
    name: 'DS1101I Glass Break Round 25 Ft',
    standby: 23,
    alarm: 23,		
},
{
    key: 148,
    mfg:'Bosch',
    name: 'DS282THS Smoke Det 2 Wire W/Heat & Sndr',
    standby: 2.5,
    alarm: 43,		
},
{
    key: 149,
    mfg:'Bosch',
    name: 'DS284ES Smoke Det 4 Wire W/Sndr&Eol Rly',
    standby: 0.9,
    alarm: 18,		
},
{
    key: 150,
    mfg:'Bosch',
    name: 'DS284IS Smoke Det 4 Wire W/Heat & Sndr',
    standby: 0.45,
    alarm: 18,		
},
{
    key: 151,
    mfg:'Bosch',
    name: 'DS284THC Smoke Det 4 Wire W/Heat & C Rly',
    standby: 0.55,
    alarm: 15,		
},
{
    key: 152,
    mfg:'Bosch',
    name: 'DS284THCS Smoke Det 4 Wire W/Ht,Rly,Sndr',
    standby: 15,
    alarm: 15,		
},
{
    key: 153,
    mfg:'Bosch',
    name: 'DS284THE 4W Smk Det W/Heat&Eol Rly',
    standby: 0,
    alarm: 75,		
},
{
    key: 154,
    mfg:'Bosch',
    name: 'DS284THS 4W Smk Det W/Heat & Sndr',
    standby: 13,
    alarm: 18,		
},
{
    key: 155,
    mfg:'Bosch',
    name: 'DS284THSR 4W Smk Det W/Ht,Sndr,Trbl',
    standby: 0,
    alarm: 125,		
},
{
    key: 156,
    mfg:'Bosch',
    name: 'DS7457i Single Point Multiplex Module With Flying Leads',
    standby: 0.5,
    alarm: 0.5,		
},
{
    key: 157,
    mfg:'Bosch',
    name: 'DS7457iF Single Point Multiplex Module With Flying Leads For Fire',
    standby: 0.5,
    alarm: 0.5,		
},
{
    key: 158,
    mfg:'Bosch',
    name: 'DS7460i Two Point Multiplex Module In Enclosure',
    standby: 1,
    alarm: 1,		
},
{
    key: 159,
    mfg:'Bosch',
    name: 'DS7461i Single Point Multiplex Module In Enclosure',
    standby: 1,
    alarm: 1,		
},
{
    key: 160,
    mfg:'Bosch',
    name: 'DS7465i Input/Output Multiplex Module In Enclosure',
    standby: 1,
    alarm: 1,		
},
{
    key: 161,
    mfg:'Bosch',
    name: 'Ds778 200ft Long Range Pir',
    standby: 18,
    alarm: 18,		
},
{
    key: 162,
    mfg:'Bosch',
    name: 'ISC-BDL2-W12G Blue Line Gen 2 Tritech 40 Ft. By 40 Ft.',
    standby: 10,
    alarm: 10,		
},
{
    key: 163,
    mfg:'Bosch',
    name: 'ISC-BDL2-WP12G Blue Line Gen 2 Tritech 40 Ft. By 40 Ft. - Pet Friendly Selectable',
    standby: 10,
    alarm: 10,		
},
{
    key: 164,
    mfg:'Bosch',
    name: 'ISC-BDL2-WP6G Blue Line Gen 2 Tritech 20 Ft. By 20 Ft. - Pet Friendly Selectable',
    standby: 10,
    alarm: 10,		
},
{
    key: 165,
    mfg:'Bosch',
    name: 'ISC-BPQ2-W12 Blue Line Gen 2 Quad Pir 40 Ft. By 40 Ft.',
    standby: 10,
    alarm: 10,		
},
{
    key: 166,
    mfg:'Bosch',
    name: 'ISC-BPR2-W12 Blue Line Gen 2 Pir 40 Ft. By 40 Ft.',
    standby: 10,
    alarm: 10,		
},
{
    key: 167,
    mfg:'Bosch',
    name: 'ISC-BPR2-WP12 Blue Line Gen 2 Pir 40 Ft. By 40 Ft. - Pet Friendly Selectable',
    standby: 10,
    alarm: 10,		
},
{
    key: 168,
    mfg:'Bosch',
    name: 'ISC-CDL1-W15G Commercial Series Tritech Detector 50 By 50 Ft.',
    standby: 10,
    alarm: 10,		
},
{
    key: 169,
    mfg:'Bosch',
    name: 'ISC-CDL1-WA12G Commercial Series Tritech Detector With Anti-Mask 40 By 40 Ft.',
    standby: 10,
    alarm: 10,		
},
{
    key: 170,
    mfg:'Bosch',
    name: 'ISC-CDL1-WA15G Commercial Series Tritech Detector With Anti-Mask 50 By 50 Ft.',
    standby: 15,
    alarm: 35,		
},
{
    key: 171,
    mfg:'Bosch',
    name: 'ISC-PDL1-W18G 60ft Professional Series Pir/Microwave Tritech',
    standby: 13,
    alarm: 25,		
},
{
    key: 172,
    mfg:'Bosch',
    name: 'ISC-PDL1-WA18G 60ft Professional Series Pir/Microwave Tritech With Multi-Point Antimask',
    standby: 18,
    alarm: 26,		
},
{
    key: 173,
    mfg:'Bosch',
    name: 'ISC-PDL1-WA18GB 60ft Professional Series Pir/Microwave Tritech With Multi-Point Antimask, Form B (N/O) Relay',
    standby: 18,
    alarm: 26,		
},
{
    key: 174,
    mfg:'Bosch',
    name: 'ISC-PDL1-WC30G 100ft Professional Series Curtain Pir/Microwave Tritech',
    standby: 18,
    alarm: 26,		
},
{
    key: 175,
    mfg:'Bosch',
    name: 'ISC-PPR1-W16 60ft Professional Series Pir',
    standby: 10,
    alarm: 15,		
},
{
    key: 176,
    mfg:'Bosch',
    name: 'ISC-PPR1-WA16G 60 Professional Series Pir With Multi-Point Antimask',
    standby: 18,
    alarm: 26,		
},
{
    key: 177,
    mfg:'Bosch',
    name: 'ISC-SK10 Shock Sensor',
    standby: 9,
    alarm: 12,		
},
{
    key: 178,
    mfg:'Bosch',
    name: 'ISN-CC1-100N Narrow Coverage Ceiling Mount Pir',
    standby: 25,
    alarm: 25,		
},
{
    key: 179,
    mfg:'Bosch',
    name: 'ISN-CC1-50W Wide Coverage Ceiling Mount Pir',
    standby: 25,
    alarm: 25,		
},
{
    key: 180,
    mfg:'Bosch',
    name: 'ISN-SM-50 Seismic Detector 50 Meter Sq',
    standby: 3,
    alarm: 6,		
},
{
    key: 181,
    mfg:'Bosch',
    name: 'ISN-SM-80 Seismic Detector 80 Meter Sq',
    standby: 3,
    alarm: 6,		
},

		
	],
    "DMP":[
		{

		},

        {
            key: 1,
            mfg:'DMP',
            name: 'XR150/XR550 Series Control Panel',
            standby: 174,
            alarm: 217,		
          },
        {
            key: 2,
            mfg:'DMP',
            name: 'XR150/XR550 Outputs 1-2',
            standby: 30,
            alarm: 30,		
          },
        {
            key: 3,
            mfg:'DMP',
            name: 'XR150/XR550 Switch Grounds 3-6 (ON)',
            standby: 5,
            alarm: 5,		
          },
        {
            key: 4,
            mfg:'DMP',
            name: 'XR150/XR550 Active Zones 1-8',
            standby: 1.6,
            alarm: 2,		
          },
        {
            key: 5,
            mfg:'DMP',
            name: 'XR150/XR550 Active Zones 9-10',
            standby: 4,
            alarm: 30,		
          },
        {
            key: 6,
            mfg:'DMP',
            name: 'XR150/XR550 2-Wire Smoke Detectors',
            standby: 0.1,
            alarm: 0.1,		
          },
        {
            key: 7,
            mfg:'DMP',
            name: '893A Dual Phone Line Module',
            standby: 12,
            alarm: 50,		
          },
        {
            key: 8,
            mfg:'DMP',
            name: '263LTE Cellular Communicator',
            standby: 20,
            alarm: 20,		
          },
        {
            key: 9,
            mfg:'DMP',
            name: '277 Buzzer Module',
            standby: 5,
            alarm: 5,		
          },
        {
            key: 10,
            mfg:'DMP',
            name: '1100X Wireless Receiver',
            standby: 25,
            alarm: 35,		
          },
        {
            key: 11,
            mfg:'DMP',
            name: '1100XH Wireless High Power Receiver',
            standby: 75,
            alarm: 102,		
          },
        {
            key: 12,
            mfg:'DMP',
            name: '860 Relay Output Module (one relay active)',
            standby: 34,
            alarm: 34,		
          },
        {
            key: 13,
            mfg:'DMP',
            name: '865 Style Y or Z Notification Module',
            standby: 26,
            alarm: 85,		
          },
        {
            key: 14,
            mfg:'DMP',
            name: '866 Style W Notification Module',
            standby: 45,
            alarm: 76,		
          },
        {
            key: 15,
            mfg:'DMP',
            name: '867 LX-Bus Style W Notification Module',
            standby: 30,
            alarm: 86,		
          },
        {
            key: 16,
            mfg:'DMP',
            name: '869 Dual Style D Initiating Module',
            standby: 25,
            alarm: 75,		
          },
        {
            key: 17,
            mfg:'DMP',
            name: '630F Remote Fire Command Center',
            standby: 63,
            alarm: 92,		
          },
        {
            key: 18,
            mfg:'DMP',
            name: '7060/7160 Thinline/7060A Aqualite Keypad',
            standby: 72,
            alarm: 87,		
          },
        {
            key: 19,
            mfg:'DMP',
            name: '7063/7163 Thinline/7063A Aqualite Keypad',
            standby: 85,
            alarm: 100,		
          },
        {
            key: 20,
            mfg:'DMP',
            name: '7070/7170 Thinline/7070A Aqualite Keypad',
            standby: 72,
            alarm: 87,		
          },
        {
            key: 21,
            mfg:'DMP',
            name: '7073/7173 Thinline/7073A Aqualite Keypad',
            standby: 85,
            alarm: 100,		
          },
        {
            key: 22,
            mfg:'DMP',
            name: '7872 Graphic Touchscreen Keypad',
            standby: 145,
            alarm: 215,		
          },
        {
            key: 23,
            mfg:'DMP',
            name: '7873 Graphic Touchscreen Keypad',
            standby: 143,
            alarm: 243,		
          },
        {
            key: 24,
            mfg:'DMP',
            name: '736P POPIT Interface Module',
            standby: 25,
            alarm: 25,		
          },
        {
            key: 25,
            mfg:'DMP',
            name: '738A Ademco Wireless Interface Module',
            standby: 75,
            alarm: 75,		
          },
        {
            key: 26,
            mfg:'DMP',
            name: '738Z+ Z-Wave Interface Module',
            standby: 40,
            alarm: 40,		
          },
        {
            key: 27,
            mfg:'DMP',
            name: '763 Wi-Fi Module',
            standby: 31,
            alarm: 31,		
          },
        {
            key: 28,
            mfg:'DMP',
            name: '710 Bus Splitter/Repeater Module',
            standby: 32,
            alarm: 32,		
          },
        {
            key: 29,
            mfg:'DMP',
            name: '711 Zone Expansion Module',
            standby: 11,
            alarm: 11,		
          },
        {
            key: 30,
            mfg:'DMP',
            name: '711 Active Zone (EOL Installed)',
            standby: 1.6,
            alarm: 2,		
          },
        {
            key: 31,
            mfg:'DMP',
            name: '711S Zone Expansion Module',
            standby: 4.2,
            alarm: 4.7,		
          },
        {
            key: 32,
            mfg:'DMP',
            name: '714 Zone Expansion Module',
            standby: 7,
            alarm: 7,		
          },
        {
            key: 33,
            mfg:'DMP',
            name: '714 Active Zones (EOL Installed)',
            standby: 1.6,
            alarm: 2,		
          },
        {
            key: 34,
            mfg:'DMP',
            name: '712-8 Zone Expansion Module',
            standby: 17,
            alarm: 17,		
          },
        {
            key: 35,
            mfg:'DMP',
            name: '712-8 Active Zones (EOL Installed)',
            standby: 1.6,
            alarm: 2,		
          },
        {
            key: 36,
            mfg:'DMP',
            name: '714-8, 714-16 Zone Expansion Module ',
            standby: 20,
            alarm: 20,		
          },
        {
            key: 37,
            mfg:'DMP',
            name: '714-8, 714-16 Active Zones (EOL Installed)',
            standby: 1.6,
            alarm: 2,		
          },
        {
            key: 38,
            mfg:'DMP',
            name: '715 Zone Expansion Module',
            standby: 7,
            alarm: 7,		
          },
        {
            key: 39,
            mfg:'DMP',
            name: '715 Active Zones (EOL Installed)',
            standby: 4,
            alarm: 30,		
          },
        {
            key: 40,
            mfg:'DMP',
            name: '715-8, 715-16 Zone Expansion Modules',
            standby: 20,
            alarm: 20,		
          },
        {
            key: 41,
            mfg:'DMP',
            name: '715-8, 715-16 Active Zones (EOL Installed)',
            standby: 4,
            alarm: 30,		
          },
        {
            key: 42,
            mfg:'DMP',
            name: '716 Output Expansion Module',
            standby: 13,
            alarm: 13,		
          },
        {
            key: 43,
            mfg:'DMP',
            name: '716 Active Form C Relays',
            standby: 0,
            alarm: 12,		
          },
        {
            key: 44,
            mfg:'DMP',
            name: '717 Graphic Annunciator Module',
            standby: 10,
            alarm: 10,		
          },
        {
            key: 45,
            mfg:'DMP',
            name: '717 Annunciator Outputs',
            standby: 0,
            alarm: 1,		
          },
        {
            key: 46,
            mfg:'DMP',
            name: '2W-BLX, 2WT-BLX Smoke Detectors',
            standby: 15,
            alarm: 35,		
          },
        {
            key: 47,
            mfg:'DMP',
            name: 'COSMOD2W Module',
            standby: 45,
            alarm: 174,		
          },
        {
            key: 48,
            mfg:'DMP',
            name: 'COSMO-2W Smoke and CO Detectors',
            standby: 1,
            alarm: 50,		
          },
        {
            key: 49,
            mfg:'DMP',
            name: '572 Indicator LED',
            standby: 20,
            alarm: 20,		
          },
	],
	}

